export interface CityData {
  slug: string;
  name: Record<string, string>;
  country: Record<string, string>;
  hotelCount: string;
  avgTemp: { summer: string; winter: string };
  tourismMillions: string;
  hvacSavingsPercent: string;
  estimatedAnnualWaste: string;
  climateNote: Record<string, string>;
}

export const cities: CityData[] = [
  {
    slug: "barcelona",
    name: { es: "Barcelona", en: "Barcelona", ca: "Barcelona", fr: "Barcelone", de: "Barcelona", it: "Barcellona", pt: "Barcelona", sv: "Barcelona", nb: "Barcelona", da: "Barcelona", pl: "Barcelona" },
    country: { es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", sv: "Spanien", nb: "Spania", da: "Spanien", pl: "Hiszpania" },
    hotelCount: "2.500+",
    avgTemp: { summer: "28°C", winter: "11°C" },
    tourismMillions: "12",
    hvacSavingsPercent: "30-35%",
    estimatedAnnualWaste: "18.000€",
    climateNote: {
      es: "Con veranos largos e intensos, los hoteles de Barcelona mantienen el aire acondicionado encendido hasta 8 meses al año. El consumo en climatización representa entre el 40% y el 50% de la factura energética.",
      en: "With long, intense summers, Barcelona hotels keep air conditioning running up to 8 months a year. HVAC accounts for 40-50% of the energy bill.",
      ca: "Amb estius llargs i intensos, els hotels de Barcelona mantenen l'aire condicionat encès fins a 8 mesos l'any. La climatització representa entre el 40% i el 50% de la factura energètica.",
      fr: "Avec des étés longs et intenses, les hôtels de Barcelone font tourner la climatisation jusqu'à 8 mois par an. Le CVC représente 40 à 50 % de la facture énergétique.",
      de: "Mit langen, intensiven Sommern laufen die Klimaanlagen in Barcelonas Hotels bis zu 8 Monate im Jahr. Die Klimatisierung macht 40–50 % der Energierechnung aus.",
      it: "Con estati lunghe e intense, gli hotel di Barcellona tengono l'aria condizionata accesa fino a 8 mesi l'anno. La climatizzazione rappresenta il 40-50% della bolletta energetica.",
      pt: "Com verões longos e intensos, os hotéis de Barcelona mantêm o ar condicionado ligado até 8 meses por ano. A climatização representa 40-50% da fatura energética.",
      sv: "Med långa, intensiva somrar håller Barcelonas hotell luftkonditioneringen igång upp till 8 månader om året. Klimatanläggningen står för 40–50 % av energiräkningen.",
      nb: "Med lange, intense somre holder hotellene i Barcelona klimaanlegget i gang opptil 8 måneder i året. Klimatisering utgjør 40–50 % av energiregningen.",
      da: "Med lange, intense somre holder Barcelonas hoteller aircondition kørende op til 8 måneder om året. Klimaanlæg udgør 40-50 % af energiregningen.",
      pl: "Podczas długich, intensywnych lat hotele w Barcelonie utrzymują klimatyzację nawet przez 8 miesięcy w roku. Klimatyzacja stanowi 40-50% rachunku za energię.",
    },
  },
  {
    slug: "madrid",
    name: { es: "Madrid", en: "Madrid", ca: "Madrid", fr: "Madrid", de: "Madrid", it: "Madrid", pt: "Madrid", sv: "Madrid", nb: "Madrid", da: "Madrid", pl: "Madryt" },
    country: { es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", sv: "Spanien", nb: "Spania", da: "Spanien", pl: "Hiszpania" },
    hotelCount: "2.000+",
    avgTemp: { summer: "33°C", winter: "6°C" },
    tourismMillions: "10",
    hvacSavingsPercent: "30-40%",
    estimatedAnnualWaste: "22.000€",
    climateNote: {
      es: "Madrid tiene un clima extremo: veranos con picos de 40°C e inviernos bajo cero. Los hoteles necesitan calefacción y aire acondicionado intensivo, lo que convierte la climatización en el mayor gasto operativo.",
      en: "Madrid has an extreme climate: summers peaking at 40°C and winters below zero. Hotels need intensive heating and cooling, making HVAC the biggest operational expense.",
      ca: "Madrid té un clima extrem: estius amb pics de 40°C i hiverns sota zero. Els hotels necessiten calefacció i aire condicionat intensiu, fent de la climatització la major despesa operativa.",
      fr: "Madrid a un climat extrême : des étés culminant à 40°C et des hivers sous zéro. Les hôtels ont besoin d'un chauffage et d'une climatisation intensifs, ce qui fait du CVC la plus grosse dépense opérationnelle.",
      de: "Madrid hat ein extremes Klima: Sommer mit Spitzen von 40°C und Winter unter null. Hotels brauchen intensive Heizung und Kühlung – die Klimatisierung ist der größte Betriebskostenfaktor.",
      it: "Madrid ha un clima estremo: estati con picchi di 40°C e inverni sotto zero. Gli hotel hanno bisogno di riscaldamento e raffreddamento intensivi, rendendo la climatizzazione la spesa operativa più grande.",
      pt: "Madrid tem um clima extremo: verões com picos de 40°C e invernos abaixo de zero. Os hotéis precisam de aquecimento e ar condicionado intensivos, tornando a climatização o maior gasto operacional.",
      sv: "Madrid har ett extremt klimat: somrar med toppar på 40°C och vintrar under noll. Hotell behöver intensiv uppvärmning och kylning, vilket gör klimatanläggningen till den största driftskostnaden.",
      nb: "Madrid har et ekstremt klima: somre med topper på 40°C og vintre under null. Hoteller trenger intensiv oppvarming og kjøling, noe som gjør klimatisering til den største driftskostnaden.",
      da: "Madrid har et ekstremt klima: somre med toppe på 40°C og vintre under nul. Hoteller har brug for intensiv opvarmning og køling, hvilket gør klimaanlæg til den største driftsudgift.",
      pl: "Madryt ma ekstremalny klimat: lata ze szczytami 40°C i zimy poniżej zera. Hotele potrzebują intensywnego ogrzewania i chłodzenia, co czyni klimatyzację największym kosztem operacyjnym.",
    },
  },
  {
    slug: "mallorca",
    name: { es: "Mallorca", en: "Mallorca", ca: "Mallorca", fr: "Majorque", de: "Mallorca", it: "Maiorca", pt: "Maiorca", sv: "Mallorca", nb: "Mallorca", da: "Mallorca", pl: "Majorka" },
    country: { es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", sv: "Spanien", nb: "Spania", da: "Spanien", pl: "Hiszpania" },
    hotelCount: "1.200+",
    avgTemp: { summer: "31°C", winter: "10°C" },
    tourismMillions: "14",
    hvacSavingsPercent: "25-35%",
    estimatedAnnualWaste: "20.000€",
    climateNote: {
      es: "Mallorca es uno de los destinos con mayor densidad hotelera de Europa. Los resorts con cientos de habitaciones tienen un consumo energético enorme en temporada alta, con el aire acondicionado funcionando las 24 horas.",
      en: "Mallorca is one of Europe's highest hotel-density destinations. Resorts with hundreds of rooms have enormous energy consumption in high season, with air conditioning running 24/7.",
      ca: "Mallorca és una de les destinacions amb major densitat hotelera d'Europa. Els resorts amb centenars d'habitacions tenen un consum energètic enorme en temporada alta, amb l'aire condicionat funcionant les 24 hores.",
      fr: "Majorque est l'une des destinations avec la plus forte densité hôtelière d'Europe. Les resorts de centaines de chambres ont une consommation énergétique énorme en haute saison, avec la climatisation 24h/24.",
      de: "Mallorca ist eines der Reiseziele mit der höchsten Hoteldichte in Europa. Resorts mit Hunderten von Zimmern haben in der Hochsaison einen enormen Energieverbrauch – mit Klimaanlagen rund um die Uhr.",
      it: "Maiorca è una delle destinazioni con la più alta densità alberghiera d'Europa. I resort con centinaia di camere hanno un consumo energetico enorme in alta stagione, con l'aria condizionata attiva 24 ore su 24.",
      pt: "Maiorca é um dos destinos com maior densidade hoteleira da Europa. Os resorts com centenas de quartos têm um consumo energético enorme na época alta, com o ar condicionado a funcionar 24 horas.",
      sv: "Mallorca är en av Europas destinationer med högst hotelldensitet. Resorts med hundratals rum har enorm energiförbrukning under högsäsongen, med luftkonditionering dygnet runt.",
      nb: "Mallorca er en av Europas destinasjoner med høyest hotelltetthet. Resorter med hundrevis av rom har enormt energiforbruk i høysesongen, med klimaanlegg døgnet rundt.",
      da: "Mallorca er en af Europas destinationer med højest hoteltæthed. Resorts med hundredvis af værelser har et enormt energiforbrug i højsæsonen, med aircondition døgnet rundt.",
      pl: "Majorka jest jednym z europejskich kierunków o największej gęstości hoteli. Resorty z setkami pokoi mają ogromne zużycie energii w sezonie, z klimatyzacją działającą 24/7.",
    },
  },
  {
    slug: "malaga",
    name: { es: "Málaga", en: "Malaga", ca: "Màlaga", fr: "Malaga", de: "Málaga", it: "Malaga", pt: "Málaga", sv: "Málaga", nb: "Málaga", da: "Málaga", pl: "Malaga" },
    country: { es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", sv: "Spanien", nb: "Spania", da: "Spanien", pl: "Hiszpania" },
    hotelCount: "800+",
    avgTemp: { summer: "30°C", winter: "12°C" },
    tourismMillions: "6",
    hvacSavingsPercent: "25-35%",
    estimatedAnnualWaste: "16.000€",
    climateNote: {
      es: "Málaga y la Costa del Sol tienen más de 300 días de sol al año. Los hoteles de la zona mantienen la climatización casi todo el año, especialmente en verano, cuando la demanda se dispara.",
      en: "Malaga and the Costa del Sol have over 300 sunny days a year. Hotels in the area keep HVAC running nearly year-round, especially in summer when demand spikes.",
      ca: "Màlaga i la Costa del Sol tenen més de 300 dies de sol l'any. Els hotels de la zona mantenen la climatització gairebé tot l'any, especialment a l'estiu, quan la demanda es dispara.",
      fr: "Malaga et la Costa del Sol ont plus de 300 jours de soleil par an. Les hôtels de la zone font tourner la climatisation presque toute l'année, surtout en été quand la demande explose.",
      de: "Málaga und die Costa del Sol haben über 300 Sonnentage im Jahr. Hotels in der Region betreiben die Klimaanlage fast das ganze Jahr über, besonders im Sommer bei Spitzennachfrage.",
      it: "Malaga e la Costa del Sol hanno più di 300 giorni di sole all'anno. Gli hotel della zona mantengono la climatizzazione quasi tutto l'anno, specialmente in estate quando la domanda esplode.",
      pt: "Málaga e a Costa del Sol têm mais de 300 dias de sol por ano. Os hotéis da zona mantêm a climatização quase o ano todo, especialmente no verão, quando a procura dispara.",
      sv: "Málaga och Costa del Sol har över 300 soldagar om året. Hotell i området håller klimatanläggningen igång nästan hela året, särskilt på sommaren när efterfrågan ökar kraftigt.",
      nb: "Málaga og Costa del Sol har over 300 solskinnsdager i året. Hoteller i området holder klimaanlegget i gang nesten hele året, spesielt om sommeren når etterspørselen skyter i været.",
      da: "Málaga og Costa del Sol har over 300 solskinsdage om året. Hoteller i området holder klimaanlægget kørende næsten hele året, især om sommeren når efterspørgslen stiger kraftigt.",
      pl: "Malaga i Costa del Sol mają ponad 300 słonecznych dni w roku. Hotele w tym regionie utrzymują klimatyzację niemal cały rok, zwłaszcza latem, gdy zapotrzebowanie gwałtownie rośnie.",
    },
  },
  {
    slug: "valencia",
    name: { es: "Valencia", en: "Valencia", ca: "València", fr: "Valence", de: "Valencia", it: "Valencia", pt: "Valência", sv: "Valencia", nb: "Valencia", da: "Valencia", pl: "Walencja" },
    country: { es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", sv: "Spanien", nb: "Spania", da: "Spanien", pl: "Hiszpania" },
    hotelCount: "700+",
    avgTemp: { summer: "29°C", winter: "11°C" },
    tourismMillions: "5",
    hvacSavingsPercent: "25-30%",
    estimatedAnnualWaste: "15.000€",
    climateNote: {
      es: "Valencia combina clima mediterráneo con una creciente oferta hotelera. Los veranos húmedos y calurosos hacen que los hoteles dependan fuertemente del aire acondicionado durante más de la mitad del año.",
      en: "Valencia combines a Mediterranean climate with a growing hotel market. Hot, humid summers mean hotels rely heavily on air conditioning for more than half the year.",
      ca: "València combina clima mediterrani amb una creixent oferta hotelera. Els estius humits i calorosos fan que els hotels depenguin fortament de l'aire condicionat durant més de la meitat de l'any.",
      fr: "Valence combine climat méditerranéen et offre hôtelière en pleine croissance. Les étés chauds et humides obligent les hôtels à compter sur la climatisation plus de la moitié de l'année.",
      de: "Valencia vereint mediterranes Klima mit einem wachsenden Hotelmarkt. Heiße, feuchte Sommer bedeuten, dass Hotels mehr als die Hälfte des Jahres stark auf Klimaanlagen angewiesen sind.",
      it: "Valencia combina clima mediterraneo con un mercato alberghiero in crescita. Le estati calde e umide fanno sì che gli hotel dipendano fortemente dall'aria condizionata per più di metà dell'anno.",
      pt: "Valência combina clima mediterrânico com uma oferta hoteleira em crescimento. Os verões quentes e húmidos fazem com que os hotéis dependam fortemente do ar condicionado durante mais de metade do ano.",
      sv: "Valencia kombinerar medelhavsklimat med en växande hotellmarknad. Varma, fuktiga somrar gör att hotell är starkt beroende av luftkonditionering mer än halva året.",
      nb: "Valencia kombinerer middelhavsklima med et voksende hotellmarked. Varme, fuktige somre betyr at hoteller er sterkt avhengige av klimaanlegg mer enn halve året.",
      da: "Valencia kombinerer middelhavsklima med et voksende hotelmarked. Varme, fugtige somre betyder, at hoteller er stærkt afhængige af aircondition mere end halvdelen af året.",
      pl: "Walencja łączy klimat śródziemnomorski z rosnącym rynkiem hotelowym. Gorące, wilgotne lata sprawiają, że hotele silnie polegają na klimatyzacji przez ponad połowę roku.",
    },
  },
  {
    slug: "sevilla",
    name: { es: "Sevilla", en: "Seville", ca: "Sevilla", fr: "Séville", de: "Sevilla", it: "Siviglia", pt: "Sevilha", sv: "Sevilla", nb: "Sevilla", da: "Sevilla", pl: "Sewilla" },
    country: { es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", sv: "Spanien", nb: "Spania", da: "Spanien", pl: "Hiszpania" },
    hotelCount: "600+",
    avgTemp: { summer: "36°C", winter: "10°C" },
    tourismMillions: "4",
    hvacSavingsPercent: "35-40%",
    estimatedAnnualWaste: "24.000€",
    climateNote: {
      es: "Sevilla es una de las ciudades más calurosas de Europa. En verano, las temperaturas superan los 40°C durante semanas. Los hoteles tienen el mayor potencial de ahorro energético en climatización de toda España.",
      en: "Seville is one of the hottest cities in Europe. In summer, temperatures exceed 40°C for weeks. Hotels here have the highest energy savings potential in HVAC across all of Spain.",
      ca: "Sevilla és una de les ciutats més caloroses d'Europa. A l'estiu, les temperatures superen els 40°C durant setmanes. Els hotels tenen el major potencial d'estalvi energètic en climatització de tota Espanya.",
      fr: "Séville est l'une des villes les plus chaudes d'Europe. En été, les températures dépassent 40°C pendant des semaines. Les hôtels y ont le plus grand potentiel d'économies d'énergie en climatisation de toute l'Espagne.",
      de: "Sevilla ist eine der heißesten Städte Europas. Im Sommer übersteigen die Temperaturen wochenlang 40°C. Hotels haben hier das größte Energiesparpotenzial bei der Klimatisierung in ganz Spanien.",
      it: "Siviglia è una delle città più calde d'Europa. In estate, le temperature superano i 40°C per settimane. Gli hotel qui hanno il maggior potenziale di risparmio energetico nella climatizzazione di tutta la Spagna.",
      pt: "Sevilha é uma das cidades mais quentes da Europa. No verão, as temperaturas ultrapassam os 40°C durante semanas. Os hotéis aqui têm o maior potencial de poupança energética em climatização de toda a Espanha.",
      sv: "Sevilla är en av Europas hetaste städer. På sommaren överstiger temperaturerna 40°C i veckor. Hotell här har den största energibesparingspotentialen inom klimatisering i hela Spanien.",
      nb: "Sevilla er en av Europas varmeste byer. Om sommeren overstiger temperaturene 40°C i ukevis. Hoteller her har det største energisparepotensialet innen klimatisering i hele Spania.",
      da: "Sevilla er en af Europas varmeste byer. Om sommeren overstiger temperaturerne 40°C i ugevis. Hoteller her har det største energibesparelsespotentiale inden for klimaanlæg i hele Spanien.",
      pl: "Sewilla jest jednym z najgorętszych miast w Europie. Latem temperatury przekraczają 40°C przez tygodnie. Hotele mają tu największy potencjał oszczędności energii na klimatyzacji w całej Hiszpanii.",
    },
  },
  {
    slug: "paris",
    name: { es: "París", en: "Paris", ca: "París", fr: "Paris", de: "Paris", it: "Parigi", pt: "Paris", sv: "Paris", nb: "Paris", da: "Paris", pl: "Paryż" },
    country: { es: "Francia", en: "France", ca: "França", fr: "France", de: "Frankreich", it: "Francia", pt: "França", sv: "Frankrike", nb: "Frankrike", da: "Frankrig", pl: "Francja" },
    hotelCount: "5.000+",
    avgTemp: { summer: "25°C", winter: "4°C" },
    tourismMillions: "38",
    hvacSavingsPercent: "20-30%",
    estimatedAnnualWaste: "20.000€",
    climateNote: {
      es: "París es el mayor mercado hotelero de Europa. Con inviernos fríos y veranos cada vez más calurosos, los hoteles necesitan calefacción y refrigeración eficientes. El potencial de optimización es enorme por el volumen de habitaciones.",
      en: "Paris is Europe's largest hotel market. With cold winters and increasingly hot summers, hotels need efficient heating and cooling. The optimization potential is enormous given the sheer volume of rooms.",
      ca: "París és el major mercat hoteler d'Europa. Amb hiverns freds i estius cada vegada més calorosos, els hotels necessiten calefacció i refrigeració eficients. El potencial d'optimització és enorme pel volum d'habitacions.",
      fr: "Paris est le plus grand marché hôtelier d'Europe. Avec des hivers froids et des étés de plus en plus chauds, les hôtels ont besoin d'un chauffage et d'une climatisation efficaces. Le potentiel d'optimisation est énorme vu le volume de chambres.",
      de: "Paris ist der größte Hotelmarkt Europas. Mit kalten Wintern und immer heißeren Sommern brauchen Hotels effiziente Heizung und Kühlung. Das Optimierungspotenzial ist angesichts der schieren Zimmerzahl enorm.",
      it: "Parigi è il più grande mercato alberghiero d'Europa. Con inverni freddi ed estati sempre più calde, gli hotel hanno bisogno di riscaldamento e raffreddamento efficienti. Il potenziale di ottimizzazione è enorme dato il volume di camere.",
      pt: "Paris é o maior mercado hoteleiro da Europa. Com invernos frios e verões cada vez mais quentes, os hotéis precisam de aquecimento e arrefecimento eficientes. O potencial de otimização é enorme dado o volume de quartos.",
      sv: "Paris är Europas största hotellmarknad. Med kalla vintrar och allt varmare somrar behöver hotell effektiv uppvärmning och kylning. Optimeringspotentialen är enorm med tanke på antalet rum.",
      nb: "Paris er Europas største hotellmarked. Med kalde vintre og stadig varmere somre trenger hoteller effektiv oppvarming og kjøling. Optimaliseringspotensialet er enormt gitt det store antallet rom.",
      da: "Paris er Europas største hotelmarked. Med kolde vintre og stadig varmere somre har hoteller brug for effektiv opvarmning og køling. Optimeringspotentialet er enormt givet det store antal værelser.",
      pl: "Paryż to największy rynek hotelowy w Europie. Z zimnymi zimami i coraz gorętszymi latami hotele potrzebują wydajnego ogrzewania i chłodzenia. Potencjał optymalizacji jest ogromny ze względu na liczbę pokoi.",
    },
  },
  {
    slug: "roma",
    name: { es: "Roma", en: "Rome", ca: "Roma", fr: "Rome", de: "Rom", it: "Roma", pt: "Roma", sv: "Rom", nb: "Roma", da: "Rom", pl: "Rzym" },
    country: { es: "Italia", en: "Italy", ca: "Itàlia", fr: "Italie", de: "Italien", it: "Italia", pt: "Itália", sv: "Italien", nb: "Italia", da: "Italien", pl: "Włochy" },
    hotelCount: "3.500+",
    avgTemp: { summer: "31°C", winter: "8°C" },
    tourismMillions: "15",
    hvacSavingsPercent: "25-35%",
    estimatedAnnualWaste: "19.000€",
    climateNote: {
      es: "Roma combina un clima mediterráneo caluroso con edificios históricos difíciles de climatizar. Los hoteles enfrentan el reto de mantener el confort sin disparar el consumo energético.",
      en: "Rome combines a hot Mediterranean climate with historic buildings that are difficult to climate-control. Hotels face the challenge of maintaining comfort without skyrocketing energy costs.",
      ca: "Roma combina un clima mediterrani calorós amb edificis històrics difícils de climatitzar. Els hotels enfronten el repte de mantenir el confort sense disparar el consum energètic.",
      fr: "Rome combine un climat méditerranéen chaud avec des bâtiments historiques difficiles à climatiser. Les hôtels font face au défi de maintenir le confort sans faire exploser les coûts énergétiques.",
      de: "Rom vereint ein heißes Mittelmeerklima mit historischen Gebäuden, die schwer zu klimatisieren sind. Hotels stehen vor der Herausforderung, Komfort zu bieten, ohne die Energiekosten in die Höhe zu treiben.",
      it: "Roma combina un clima mediterraneo caldo con edifici storici difficili da climatizzare. Gli hotel affrontano la sfida di mantenere il comfort senza far schizzare i costi energetici.",
      pt: "Roma combina um clima mediterrânico quente com edifícios históricos difíceis de climatizar. Os hotéis enfrentam o desafio de manter o conforto sem disparar os custos energéticos.",
      sv: "Rom kombinerar ett varmt medelhavsklimat med historiska byggnader som är svåra att klimatisera. Hotell står inför utmaningen att upprätthålla komfort utan att energikostnaderna skjuter i höjden.",
      nb: "Roma kombinerer et varmt middelhavsklima med historiske bygninger som er vanskelige å klimatisere. Hoteller står overfor utfordringen med å opprettholde komfort uten at energikostnadene skyter i været.",
      da: "Rom kombinerer et varmt middelhavsklima med historiske bygninger, der er svære at klimatisere. Hoteller står over for udfordringen med at opretholde komfort uden at energiomkostningerne stiger voldsomt.",
      pl: "Rzym łączy gorący klimat śródziemnomorski z historycznymi budynkami trudnymi do klimatyzowania. Hotele stają przed wyzwaniem utrzymania komfortu bez gwałtownego wzrostu kosztów energii.",
    },
  },
  {
    slug: "lisboa",
    name: { es: "Lisboa", en: "Lisbon", ca: "Lisboa", fr: "Lisbonne", de: "Lissabon", it: "Lisbona", pt: "Lisboa", sv: "Lissabon", nb: "Lisboa", da: "Lissabon", pl: "Lizbona" },
    country: { es: "Portugal", en: "Portugal", ca: "Portugal", fr: "Portugal", de: "Portugal", it: "Portogallo", pt: "Portugal", sv: "Portugal", nb: "Portugal", da: "Portugal", pl: "Portugalia" },
    hotelCount: "1.500+",
    avgTemp: { summer: "28°C", winter: "11°C" },
    tourismMillions: "7",
    hvacSavingsPercent: "25-30%",
    estimatedAnnualWaste: "16.000€",
    climateNote: {
      es: "Lisboa ha duplicado su oferta hotelera en la última década. Con veranos calurosos y un boom turístico, la eficiencia energética se ha convertido en una prioridad para los operadores hoteleros.",
      en: "Lisbon has doubled its hotel supply in the last decade. With hot summers and a tourism boom, energy efficiency has become a priority for hotel operators.",
      ca: "Lisboa ha duplicat la seva oferta hotelera en l'última dècada. Amb estius calorosos i un boom turístic, l'eficiència energètica s'ha convertit en una prioritat per als operadors hotelers.",
      fr: "Lisbonne a doublé son offre hôtelière en dix ans. Avec des étés chauds et un boom touristique, l'efficacité énergétique est devenue une priorité pour les opérateurs hôteliers.",
      de: "Lissabon hat sein Hotelangebot im letzten Jahrzehnt verdoppelt. Mit heißen Sommern und einem Tourismusboom ist Energieeffizienz zu einer Priorität für Hotelbetreiber geworden.",
      it: "Lisbona ha raddoppiato la sua offerta alberghiera nell'ultimo decennio. Con estati calde e un boom turistico, l'efficienza energetica è diventata una priorità per gli operatori alberghieri.",
      pt: "Lisboa duplicou a sua oferta hoteleira na última década. Com verões quentes e um boom turístico, a eficiência energética tornou-se uma prioridade para os operadores hoteleiros.",
      sv: "Lissabon har fördubblat sitt hotellutbud under det senaste decenniet. Med varma somrar och en turistboom har energieffektivitet blivit en prioritet för hotelloperatörer.",
      nb: "Lisboa har doblet sitt hotelltilbud det siste tiåret. Med varme somre og en turistboom har energieffektivitet blitt en prioritet for hotelloperatører.",
      da: "Lissabon har fordoblet sit hoteludbud i det seneste årti. Med varme somre og et turistboom er energieffektivitet blevet en prioritet for hoteloperatører.",
      pl: "Lizbona podwoiła swoją bazę hotelową w ciągu ostatniej dekady. Przy gorących latach i boomie turystycznym efektywność energetyczna stała się priorytetem dla operatorów hotelowych.",
    },
  },
  {
    slug: "berlin",
    name: { es: "Berlín", en: "Berlin", ca: "Berlín", fr: "Berlin", de: "Berlin", it: "Berlino", pt: "Berlim", sv: "Berlin", nb: "Berlin", da: "Berlin", pl: "Berlin" },
    country: { es: "Alemania", en: "Germany", ca: "Alemanya", fr: "Allemagne", de: "Deutschland", it: "Germania", pt: "Alemanha", sv: "Tyskland", nb: "Tyskland", da: "Tyskland", pl: "Niemcy" },
    hotelCount: "2.800+",
    avgTemp: { summer: "24°C", winter: "1°C" },
    tourismMillions: "14",
    hvacSavingsPercent: "20-30%",
    estimatedAnnualWaste: "18.000€",
    climateNote: {
      es: "Berlín tiene inviernos largos y fríos que requieren calefacción intensiva. Alemania es líder en regulación energética, y los hoteles enfrentan cada vez más presión para reducir su huella de carbono.",
      en: "Berlin has long, cold winters that require intensive heating. Germany leads in energy regulation, and hotels face increasing pressure to reduce their carbon footprint.",
      ca: "Berlín té hiverns llargs i freds que requereixen calefacció intensiva. Alemanya és líder en regulació energètica, i els hotels enfronten cada vegada més pressió per reduir la seva petjada de carboni.",
      fr: "Berlin a des hivers longs et froids nécessitant un chauffage intensif. L'Allemagne est leader en réglementation énergétique, et les hôtels font face à une pression croissante pour réduire leur empreinte carbone.",
      de: "Berlin hat lange, kalte Winter, die intensive Heizung erfordern. Deutschland ist führend bei der Energieregulierung, und Hotels stehen unter zunehmendem Druck, ihren CO₂-Fußabdruck zu reduzieren.",
      it: "Berlino ha inverni lunghi e freddi che richiedono riscaldamento intensivo. La Germania è leader nella regolamentazione energetica, e gli hotel affrontano una pressione crescente per ridurre la loro impronta di carbonio.",
      pt: "Berlim tem invernos longos e frios que requerem aquecimento intensivo. A Alemanha é líder em regulamentação energética, e os hotéis enfrentam cada vez mais pressão para reduzir a sua pegada de carbono.",
      sv: "Berlin har långa, kalla vintrar som kräver intensiv uppvärmning. Tyskland leder inom energireglering, och hotell möter ökande tryck att minska sitt koldioxidavtryck.",
      nb: "Berlin har lange, kalde vintre som krever intensiv oppvarming. Tyskland leder innen energiregulering, og hoteller møter økende press for å redusere sitt karbonfotavtrykk.",
      da: "Berlin har lange, kolde vintre, der kræver intensiv opvarmning. Tyskland er førende inden for energiregulering, og hoteller står over for stigende pres for at reducere deres CO₂-aftryk.",
      pl: "Berlin ma długie, zimne zimy wymagające intensywnego ogrzewania. Niemcy są liderem w regulacjach energetycznych, a hotele stoją pod rosnącą presją redukcji śladu węglowego.",
    },
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return cities.map((c) => c.slug);
}
